/* videoteca.h generated by valac 0.17.0, the Vala compiler, do not modify */


#ifndef __VIDEOTECA_H__
#define __VIDEOTECA_H__

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <libpeas/peas.h>
#include <stdlib.h>
#include <string.h>
#include <libpeas-gtk/peas-gtk.h>

G_BEGIN_DECLS


#define VIDEOTECA_TYPE_VIDEO_WIDGET (videoteca_video_widget_get_type ())
#define VIDEOTECA_VIDEO_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VIDEOTECA_TYPE_VIDEO_WIDGET, VideotecaVideoWidget))
#define VIDEOTECA_VIDEO_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VIDEOTECA_TYPE_VIDEO_WIDGET, VideotecaVideoWidgetClass))
#define VIDEOTECA_IS_VIDEO_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VIDEOTECA_TYPE_VIDEO_WIDGET))
#define VIDEOTECA_IS_VIDEO_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VIDEOTECA_TYPE_VIDEO_WIDGET))
#define VIDEOTECA_VIDEO_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VIDEOTECA_TYPE_VIDEO_WIDGET, VideotecaVideoWidgetClass))

typedef struct _VideotecaVideoWidget VideotecaVideoWidget;
typedef struct _VideotecaVideoWidgetClass VideotecaVideoWidgetClass;
typedef struct _VideotecaVideoWidgetPrivate VideotecaVideoWidgetPrivate;

#define VIDEOTECA_TYPE_MAIN_WINDOW (videoteca_main_window_get_type ())
#define VIDEOTECA_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VIDEOTECA_TYPE_MAIN_WINDOW, VideotecaMainWindow))
#define VIDEOTECA_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VIDEOTECA_TYPE_MAIN_WINDOW, VideotecaMainWindowClass))
#define VIDEOTECA_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VIDEOTECA_TYPE_MAIN_WINDOW))
#define VIDEOTECA_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VIDEOTECA_TYPE_MAIN_WINDOW))
#define VIDEOTECA_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VIDEOTECA_TYPE_MAIN_WINDOW, VideotecaMainWindowClass))

typedef struct _VideotecaMainWindow VideotecaMainWindow;
typedef struct _VideotecaMainWindowClass VideotecaMainWindowClass;
typedef struct _VideotecaMainWindowPrivate VideotecaMainWindowPrivate;

#define VIDEOTECA_TYPE_PLUGINS (videoteca_plugins_get_type ())
#define VIDEOTECA_PLUGINS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VIDEOTECA_TYPE_PLUGINS, VideotecaPlugins))
#define VIDEOTECA_PLUGINS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VIDEOTECA_TYPE_PLUGINS, VideotecaPluginsClass))
#define VIDEOTECA_IS_PLUGINS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VIDEOTECA_TYPE_PLUGINS))
#define VIDEOTECA_IS_PLUGINS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VIDEOTECA_TYPE_PLUGINS))
#define VIDEOTECA_PLUGINS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VIDEOTECA_TYPE_PLUGINS, VideotecaPluginsClass))

typedef struct _VideotecaPlugins VideotecaPlugins;
typedef struct _VideotecaPluginsClass VideotecaPluginsClass;

#define VIDEOTECA_TYPE_PREFERENCES_WINDOW (videoteca_preferences_window_get_type ())
#define VIDEOTECA_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VIDEOTECA_TYPE_PREFERENCES_WINDOW, VideotecaPreferencesWindow))
#define VIDEOTECA_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VIDEOTECA_TYPE_PREFERENCES_WINDOW, VideotecaPreferencesWindowClass))
#define VIDEOTECA_IS_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VIDEOTECA_TYPE_PREFERENCES_WINDOW))
#define VIDEOTECA_IS_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VIDEOTECA_TYPE_PREFERENCES_WINDOW))
#define VIDEOTECA_PREFERENCES_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VIDEOTECA_TYPE_PREFERENCES_WINDOW, VideotecaPreferencesWindowClass))

typedef struct _VideotecaPreferencesWindow VideotecaPreferencesWindow;
typedef struct _VideotecaPreferencesWindowClass VideotecaPreferencesWindowClass;
typedef struct _VideotecaPreferencesWindowPrivate VideotecaPreferencesWindowPrivate;
typedef struct _VideotecaPluginsPrivate VideotecaPluginsPrivate;

struct _VideotecaVideoWidget {
	GObject parent_instance;
	VideotecaVideoWidgetPrivate * priv;
};

struct _VideotecaVideoWidgetClass {
	GObjectClass parent_class;
};

struct _VideotecaMainWindow {
	GtkWindow parent_instance;
	VideotecaMainWindowPrivate * priv;
	GtkMenuBar* menubar;
	GtkToolbar* toolbar;
};

struct _VideotecaMainWindowClass {
	GtkWindowClass parent_class;
};

typedef GtkWindow* (*VideotecaWindowConstructor) (VideotecaPlugins* plugins, void* user_data);
struct _VideotecaPreferencesWindow {
	GtkWindow parent_instance;
	VideotecaPreferencesWindowPrivate * priv;
};

struct _VideotecaPreferencesWindowClass {
	GtkWindowClass parent_class;
};

struct _VideotecaPlugins {
	GObject parent_instance;
	VideotecaPluginsPrivate * priv;
	PeasEngine* engine;
	PeasExtensionSet* extension_set;
};

struct _VideotecaPluginsClass {
	GObjectClass parent_class;
};


GType videoteca_video_widget_get_type (void) G_GNUC_CONST;
VideotecaVideoWidget* videoteca_video_widget_new (void);
VideotecaVideoWidget* videoteca_video_widget_construct (GType object_type);
GType videoteca_main_window_get_type (void) G_GNUC_CONST;
GType videoteca_plugins_get_type (void) G_GNUC_CONST;
VideotecaMainWindow* videoteca_main_window_new (VideotecaVideoWidget* video_widget, GObject* plugins, VideotecaWindowConstructor preferences_window_constructor, void* preferences_window_constructor_target);
VideotecaMainWindow* videoteca_main_window_construct (GType object_type, VideotecaVideoWidget* video_widget, GObject* plugins, VideotecaWindowConstructor preferences_window_constructor, void* preferences_window_constructor_target);
GtkToolbar* videoteca_main_window_get_toolbar (VideotecaMainWindow* self);
GType videoteca_preferences_window_get_type (void) G_GNUC_CONST;
VideotecaPreferencesWindow* videoteca_preferences_window_new (VideotecaPlugins* plugins);
VideotecaPreferencesWindow* videoteca_preferences_window_construct (GType object_type, VideotecaPlugins* plugins);
void videoteca_preferences_window_create_widgets (VideotecaPreferencesWindow* self);
VideotecaPlugins* videoteca_plugins_new (const gchar* path);
VideotecaPlugins* videoteca_plugins_construct (GType object_type, const gchar* path);
void videoteca_plugins_load (VideotecaPlugins* self);
PeasGtkPluginManager* videoteca_plugins_make_widget (VideotecaPlugins* self);
void videoteca_plugins_extension_update_state (VideotecaPlugins* self, PeasPluginInfo* info, PeasExtension* exten);
PeasExtensionSet* videoteca_plugins_setup_extension_set (VideotecaPlugins* self, VideotecaMainWindow* window);
VideotecaMainWindow* videoteca_make_mainwindow (VideotecaPlugins* plugins);
GtkWindow* videoteca_make_preferences_window (VideotecaPlugins* plugins);
VideotecaPlugins* videoteca_make_plugins (void);


G_END_DECLS

#endif
